# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none  # Không trigger theo push, chỉ theo schedule hoặc manual

schedules:
- cron: "8,38 * * * *"
  displayName: Every hour at :08 and :38
  branches:
    include:
      - main  # hoặc nhánh bạn muốn
  always: true

pr: none  # Không trigger theo pull request

jobs:
- job: CaptureScreenshots
  timeoutInMinutes: 20
  strategy:
    matrix:
      # windows1: { vmImage: 'windows-2019' }
      # windows2: { vmImage: 'windows-2019' }
      # windows3: { vmImage: 'windows-2019' }
      # windows4: { vmImage: 'windows-2019' }
      # windows5: { vmImage: 'windows-2019' }
      # windows6: { vmImage: 'windows-2019' }
      # windows7: { vmImage: 'windows-2019' }
      # windows8: { vmImage: 'windows-2019' }
      # windows9: { vmImage: 'windows-2019' }
      # windows10: { vmImage: 'windows-2019' }
      # latest1: { vmImage: 'windows-latest' }
      # latest2: { vmImage: 'windows-latest' }
      # latest3: { vmImage: 'windows-latest' }
      # latest4: { vmImage: 'windows-latest' }
      # latest5: { vmImage: 'windows-latest' }
      # latest6: { vmImage: 'windows-latest' }
      # latest7: { vmImage: 'windows-latest' }
      # latest8: { vmImage: 'windows-latest' }
      latest9: { vmImage: 'windows-latest' }

  pool:
    vmImage: $(vmImage)

  continueOnError: true

  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true

  - script: |
      pip install undetected-chromedriver selenium chromedriver_autoinstaller pyautogui fake-useragent
    displayName: 'Install dependencies'

  - script: |
      python videzz_video.py
    displayName: 'Run Selenium script'

  - task: PublishBuildArtifacts@1
    displayName: 'Archive screenshots'
    condition: always()
    inputs:
      PathtoPublish: '**/*.png'
      ArtifactName: screenshots
      publishLocation: 'Container'
