app = "videzz-video"
primary_region = "iad"  # Chọn region US phù hợp: iad, sjc, ord, ewr...

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[experimental]
  auto_rollback = true

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1024
